repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          # Due to weird the pre-commit authors being weird, you need to use
          # this very silly workaround
          #
          # There _was_ an explanation, but they hid issues because people were
          # mad at them for doing this
          - prettier@3.3.3

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v9.14.0"
    hooks:
      - id: eslint
        files: \.(c?[jt]s|vue)$
        types: [file]
        additional_dependencies:
          - "@eslint/js@9.14.0"
          - "@types/eslint__js@8.42.3"
          - "eslint-config-prettier@9.1.0"
          - "eslint@9.14.0"
          - "typescript-eslint@8.12.2"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-illegal-windows-names
      - id: check-json
        # The pre-commit guy doesn't believe in json5 :/
        exclude: "tsconfig.json"
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
